{{- if .Values.backendconfig -}}
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ .Release.Name }}-ing
spec:
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 10
    requestPath: "/healthz"
    healthyThreshold: 2
    unhealthyThreshold: 2
    type: HTTP
  connectionDraining:
    drainingTimeoutSec: 60
  sessionAffinity:
    affinityType: "CLIENT_IP"
  timeoutSec: 60
{{- end -}}
