{{- $name := .Values.selector -}}
{{- $data := dict "name" $name "Chart" .Chart "Release" .Release "Values" .Values -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ing
  labels:
    app: {{ template "ingress.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
  annotations:
    {{- if .Values.backendconfig }}
    cloud.google.com/backend-config: '{"ports": {"80":"{{ .Release.Name }}-ing"}}'
    {{- end }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: {{ .Values.port }}
      protocol: TCP
  selector:
    app: {{ .Values.selector }}
    release: {{ .Release.Name }}
