{{- $name := "db" -}}
{{- $data := dict "Chart" .Chart "Release" .Release "Values" .Values -}}
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ include "db.fullname" . }}
  labels:
    {{- include "db.labels" $data | nindent 4 }}
subsets:
  - addresses:
      - ip: {{ $.Values.ip }}
    ports:
      - port: {{ $.Values.port }}
