{{- $name := "db" -}}
{{- $data := dict "Chart" .Chart "Release" .Release "Values" .Values -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "db.fullname" . }}
  labels:
    {{- include "db.labels" $data | nindent 4 }}
spec:
  ports:
    - protocol: TCP
      port: {{ $.Values.port }}
      targetPort: {{ $.Values.port }}
