{{- $name := "varnish" -}}
{{- $data := dict "name" $name "Chart" .Chart "Release" .Release "Values" .Values -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "varnish.fullname" . }}
  labels:
    app: {{ template "varnish.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
  annotations:
    cloud.google.com/backend-config: '{"ports": {"80":"{{ include "varnish.fullname" . }}"}}'
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http-varnish
  selector:
    app: {{ template "varnish.name" . }}
    release: {{ .Release.Name }}