{{- if .Values.clean_refresh_token_cron.enabled }}
{{- $fullName := include "api.fullname" . -}}

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ $fullName }}-clear-refresh-tokens
spec:
  schedule: {{ $.Values.clean_refresh_token_cron.schedule }}
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: clear-refresh-tokens
              image: {{ $.Values.php.image.repository }}:{{ $.Values.php.image.tag }}
              args:
                - /bin/sh
                - -c
                - bin/console gesdinet:jwt:clear "$(date '+%Y-%m-%d %H:%M:%S' -d '1 day ago')"
              envFrom:
{{- if .Values.php.envFrom }}
{{ toYaml .Values.php.envFrom | indent 16 }}
{{- end }}
              env:
                {{- range $key, $val := .Values.php.extraEnvVars }}
                - name: {{ $key }}
                  value: {{ $val | quote }}
                {{- end }}
          restartPolicy: OnFailure
{{- end }}
