apiVersion: v2
description: API Chart based on nginx and php-fpm
name: api
version: 4.0.2
appVersion: 4.0.2
home: https://www.thecolvinco.com
icon: view-source:https://www.thecolvinco.com/favicon-192.png
sources:
  - https://github.com/TheColvinCo/helm-charts
keywords:
  - nginx
  - php
  - php-fpm
  - api
maintainers:
  - name: Marçal Darnaculleta
    email: m.darnaculleta@thecolvinco.com
  - name: Andrea De Pirro
    email: andrea.depirro@thecolvinco.com
